# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account1',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Role'),
        ),
    ]
