# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170714_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级信息表', 'verbose_name_plural': '班级信息表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息表', 'verbose_name_plural': '课程信息表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已报名'), (1, '已退费'), (2, '未报名')], default=2, verbose_name='来源'),
        ),
    ]
